### ISSUE TITLE
Pinout / schematic request.

### ISSUE THREAD

**Issue by 9600** [pimoroni/microdot-phat#7]
Attempted to connect one up via wire jumpers instead of just plugging it onto a Pi.

Connected pins 1, 2, 3, 4, 5 & 9, but it's not being detected via i2c-detect. What pins need to be connected?

**Comment by Gadgetoid** [comment]
It's a heck of a tightly routed board, it's likely you'll need to connect _all_ the ground pins. This isn't usually required, since there's plenty of ground plane to join them on other boards, but in this case hook 'em all up for now and if I find time I'll look over the BRD file and see if I can figure out which are absolutely necessary.

**Comment by 9600** [comment]
Connected all grounds, 3V3 and 5V, but still not being detected, so for my sanity I'm going to test on another Pi where I can get access to all pins and stick it on P1. However, a definitive list would be nice...

**Comment by Gadgetoid** [comment]
I looked back over the board design this morning. Despite the tight routing the ground plane connects all ground pins, and leaves nothing isolated. Connecting _any_ ground pin should get you up and running.

Depending on your use-case, that may suffice, but the Matrix drivers are very noisy when PWMing the displays.

If I were to go with a list, I'd say Physical 6, 20 and 34, ( which, from eye, look "electrically closest"- ergo the path of least resistance; taking into account ohms per square ) but you could just as easily use 6, 9, 25 and 39.
